### ISSUE TITLE
Throttle is skipping the last event

### ISSUE THREAD

**Issue by infi-pc** [github/mini-throttle#17]
Hi, not sure if I am confused or if it is a bug, but while debounce works well, the throttle is skipping the last event (number 10 in the example "marble chart" in Readme). It seems it is not resetting the time window after the given timeout, other libraries are doing it (I checked Rx and Lodash)

a minimal example comparing mini-throttle with lodash throttle: https://codesandbox.io/p/sandbox/damp-browser-fyd2g4?file=%2Fsrc%2Findex.js%3A1%2C1-26%2C1 

slow and fast events:

https://github.com/github/mini-throttle/assets/2264725/e91e1783-68e9-4530-87cf-b52480d933c1

https://github.com/github/mini-throttle/assets/2264725/9d3f2dce-55ae-480d-ad15-b4a58f60d991

**Comment by keithamus** [comment]
This looks like a bug. /cc @github/web-systems-reviewers

**Comment by jfuchs** [comment]
Looks like this was already fixed in https://github.com/github/mini-throttle/pull/15 but the publish was interrupted. 2.1.1 is now published and I was able to validate it against your codesandbox. Thanks for the bug report @infi-pc!
